Complete
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-levialmog pull request #1
Opened 2022-03-19 15:49 UTC by levialmog

Ready for your review.

2022-03-24 06:09 UTC, talbarfm requested changes

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +def days_between(d1, d2):
where is the documentations?

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +def days_between(d1, d2):
never ever ever use single character variables - even i and j in for loops should be avoided if possible. it makes big code terrible to read

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +def days_between(d1, d2):
why d1 and d2? I think these dates have more meaning besides the fact that we have to of them - how about start_date and end_date? these are good names in my opinion

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +def days_between(d1, d2):
unless you use abs, in that case date1 date2 is fine

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +    date1, date2 = input("Enter two dates in format YYYY-MM-DD and date1 smaller than date2: ").split()
this message to the user is not that clear

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +    date1, date2 = input("Enter two dates in format YYYY-MM-DD and date1 smaller than date2: ").split()
you dont need date 1 to be smaller then date 2 if you use the abs trick

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +    if re.match('[0-9]{4}-[0-9]{2}-[0-9]{2}', date1) and re.match('[0-9]{4}-[0-9]{2}-[0-9]{2}', date2) and date1 < date2:
I really like the use of regex as a concept! but in here its redundant - you don't have to implement this logic yourself because python has it in one of its packages. in cases like this, I want a little alarm to ring in your head - "Should this code exist? maybe someone already wrote something like this?" 
Read this and fix :) 
https://www.programiz.com/python-programming/datetime/strptime

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +        time_between_dates = days_between(date1, date2)
your function is doing multiple things - separate the monday logic from the random day logic, and the input from the logic

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +    date1, date2 = input("Enter two dates in format YYYY-MM-DD and date1 smaller than date2: ").split()
When you write code, you should aim to write it as "pure" a possible - avoid IO (input output) operations near logic. why is that? if you want to use this logic elsewhere - for example, receive a path from a place other than the standart input,

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +i_have_no_vinaigrette()
https://www.freecodecamp.org/news/if-name-main-python-example/

2022-03-24 06:09 UTC, talbarfm commented on I_have_no_vinaigrette.py
> +i_have_no_vinaigrette()
Dont call the logic just at the outside, its a problem when this file is supposed to be imported. read the link and change the code

2022-03-30 07:00 UTC, lovodkin93 requested changes

2022-03-30 07:00 UTC, lovodkin93 commented on I_have_no_vinaigrette.py
> +    d1 = datetime.datetime.strptime(start_date, "%Y-%m-%d")
just like Tal said - do not use single-character variable names.

2022-03-30 07:00 UTC, lovodkin93 commented on I_have_no_vinaigrette.py
> +def days_between(start_date, end_date):
and the documentation is still missing

2022-04-18 22:57 UTC, merged