Complete
ScaleUp-Academy-ExcellenTeam22/yam-mesika-weeks-5-6-levialmog pull request #3
Opened 2022-03-19 16:56 UTC by levialmog

Ready for your review

2022-03-25 19:05 UTC, talbarfm requested changes

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    if args is None:
![image](https://user-images.githubusercontent.com/13467749/159850042-6d4f352d-12f3-445d-973e-bdd0a1a01e24.png)
Will args ever be None?

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    if args is None:
Use Ipython to check things like this

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    for value in args:
use nested list comprehention and zip for this

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +cup_of_join([1, 2], [2, 3], [3, 4])
https://www.freecodecamp.org/news/if-name-main-python-example/ 
Read this and fix

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    for value in args:
Or itertools.chain

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    res = []
res? pick a better name?

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +def cup_of_join(*args, sep='-'):
Cant you say anything more specific about these *args? maybe a better name?

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +def cup_of_join(*args, sep='-'):
Dont use abbreviations - separator not sep

2022-03-25 19:05 UTC, talbarfm commented on cup_of_join.py
> +    print(res)
Use returns, dont coupe input output operations (like print and input) with code logic. Print it outside

2022-03-30 06:50 UTC, lovodkin93 approved these changes
looks very good.

2022-03-30 08:16 UTC, merged